CREATE TABLE movies
(movieId INT, title STRING, genres STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE tags
(userId INT, movieId INT, tag STRING, `timestamp` TIMESTAMP)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE ratings
(userId INT, movieId INT, rating NUMERIC(10, 4), `timestamp` TIMESTAMP)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE genome_scores
(movieId INT, tagId INT, relavance DOUBLE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE genome_tags
(tagId INT, tag STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
STORED AS TEXTFILE;
